# Generated by Django 4.1.7 on 2023-03-11 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('cpf', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('number', models.IntegerField()),
                ('complement', models.CharField(blank=True, max_length=50)),
                ('neighborhood', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FinancialInstitution',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('cnpj', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('version', models.CharField(max_length=50)),
                ('chassis', models.CharField(max_length=50)),
                ('plate', models.CharField(max_length=50)),
                ('mileage', models.IntegerField()),
                ('year', models.IntegerField()),
                ('color', models.CharField(max_length=50)),
                ('fuel_type', models.CharField(max_length=50)),
                ('transmission', models.CharField(max_length=50)),
                ('doors', models.IntegerField()),
                ('category', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('minimum_bid', models.FloatField()),
                ('minimum_bid_increment', models.FloatField()),
                ('description', models.TextField()),
                ('images_url', models.CharField(max_length=200)),
                ('auction_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.auction')),
            ],
        ),
        migrations.CreateModel(
            name='RealEstate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('terreno', 'Terreno'), ('casa', 'Casa'), ('apartamento', 'Apartamento'), ('cormercial', 'Comercial'), ('rural', 'Rural')], max_length=100)),
                ('address', models.CharField(max_length=50)),
                ('number', models.IntegerField()),
                ('complement', models.CharField(max_length=50)),
                ('neighborhood', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('zip_code', models.IntegerField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('area_total', models.FloatField()),
                ('building_area', models.FloatField()),
                ('status', models.CharField(choices=[('ocupado', 'Ocupado'), ('desocupado', 'Desocupado')], max_length=100)),
                ('condition', models.CharField(choices=[('novo', 'Novo'), ('exige_reforma', 'Exige reforma'), ('possui_dividas', 'Possui dividas')], max_length=100)),
                ('rooms', models.IntegerField()),
                ('minimum_bid', models.FloatField()),
                ('minimum_bid_increment', models.FloatField()),
                ('description', models.TextField()),
                ('images_url', models.CharField(max_length=200)),
                ('documents_url', models.CharField(max_length=200)),
                ('auction_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.auction')),
            ],
        ),
        migrations.CreateModel(
            name='BidHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.FloatField()),
                ('status', models.CharField(max_length=50)),
                ('auction_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.auction')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.customer')),
                ('real_estate_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.realestate')),
                ('vehicle_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.vehicle')),
            ],
        ),
        migrations.AddField(
            model_name='auction',
            name='financial_institution_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.financialinstitution'),
        ),
    ]
