# Generated by Django 4.1.7 on 2023-03-20 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_auction_name_alter_auction_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidhistory',
            name='real_estate_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.realestate'),
        ),
        migrations.AlterField(
            model_name='bidhistory',
            name='vehicle_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.vehicle'),
        ),
    ]
