FROM node:alpine
ENV NODE_ENV development

WORKDIR /app

COPY app/package.json /app/package.json
COPY app/package-lock.json /app/package-lock.json

RUN npm ci

ENV CI=true
COPY /app /app

ENV PORT=3000

CMD [ "npm", "start" ]