version: '3'
services:
  db:
    image: 'postgres:latest'
    container_name: auctions-system-db
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - '30432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: postgres
    restart: always
  api:
    build: 
      context: ./backend
      dockerfile: Dockerfile.backend
    container_name: auctions-system-api
    command: python manage.py migrate && python manage.py runserver 0.0.0.0:8000
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - '8000:8000'
    env_file:
      - ./backend/.env
    environment:
      PGHOST: db
      PGPORT: 5432
      PGUSER: postgres
      PGPASSWORD: mysecretpassword
      PGDATABASE: postgres
    depends_on:
      - db
    volumes:
      - ./backend:/code
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.frontend
    container_name: auctions-system-frontend
    ports:
      - '3000:3000'
    depends_on:
      - api
    volumes:
      - ./frontend/app:/app
    restart: always
